services:
  backup:
    build: .
    container_name: nova-backups
    restart: unless-stopped

    env_file:
      - .env

    environment:
      TZ: Asia/Jakarta
      RAR_PASSWORD: ${RAR_PASSWORD}

    user: "0:0"

    volumes:
      - /home:/host/home:ro
      - /root:/host/root:ro
      - ${BACKUP_DESTINATION}:/backup
      - ${RECOVERY_DESTINATION}:/recovery
      - ./logs:/app/logs

