services:
  backup:
    build: .
    container_name: nova-backups
    restart: unless-stopped
    cpus: ${CPU_LIMIT}
    mem_limit: ${MEM_LIMIT}
    
    env_file:
      - .env

    environment:
      TZ: Asia/Jakarta
      RAR_PASSWORD: ${RAR_PASSWORD}

    user: "0:0"

    volumes:
      - /home:/host/home:ro
      - /root:/host/root:ro
      - /www:/host/www:ro
      - ${BACKUP_DESTINATION}:/backup
      - ${RECOVERY_DESTINATION}:/recovery
      - ./logs:/app/logs

    networks:
      - mysql_network
      - sqlserver_network

networks:
  mysql_network:
    external: true
    name: mysql_network

  sqlserver_network:
    external: true
    name: sqlserver_network


